- name: Deploy selected service container
  hosts: ec2
  become: yes

  tasks:
    - name: Pull Docker image
      docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Run container
      docker_container:
        name: "{{ service_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        ports:
          - "8080:8080"




