---
- name: Deploy selected service to EC2
  hosts: web
  become: yes

  vars:
    image_name: "shmulik41/{{ service_name }}:latest"

  tasks:
    - name: Pull Docker image
      shell: docker pull {{ image_name }}

    - name: Stop and remove existing container
      shell: docker rm -f {{ service_name }} || true

    - name: Run new container
      shell: docker run -d --name {{ service_name }} -p 8080:80 {{ image_name }}


