- name: Deploy selected service container
  hosts: ec2
  become: yes

  vars:
    image_name: "shmulik41/{{ service_name }}:latest"
    container_name: "{{ service_name }}"

  tasks:
    - name: Pull Docker image
      docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Run container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        ports:
          - "{{ '8080:8080' if service_name == 'service1' else '8081:8080' }}"







